language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PINS="mirage-flow.2.0.0:. mirage-flow-combinators.2.0.0:. mirage-flow-unix.2.0.0:. mirage-clock.3.0.0:git+https://github.com/hannesm/mirage-clock.git#easy"
  matrix:
  - OCAML_VERSION=4.06 PACKAGE="mirage-flow-combinators"
  - OCAML_VERSION=4.06 PACKAGE="mirage-flow-unix"
  - OCAML_VERSION=4.07 PACKAGE="mirage-flow-combinators"
  - OCAML_VERSION=4.07 PACKAGE="mirage-flow-unix"
  - OCAML_VERSION=4.08 PACKAGE="mirage-flow"
  - OCAML_VERSION=4.08 PACKAGE="mirage-flow-combinators"
  - OCAML_VERSION=4.08 PACKAGE="mirage-flow-unix"
  - OCAML_VERSION=4.09 PACKAGE="mirage-flow"
  - OCAML_VERSION=4.09 PACKAGE="mirage-flow-combinators"
  - OCAML_VERSION=4.09 PACKAGE="mirage-flow-unix"
